import 'package:flutter/material.dart';

Map<String, Color> appColors = {
  'Accent': const Color(0xFF41B60A),
  'Accent2': const Color(0xFFB66E0A),
  'Accent3': const Color(0xFF0A6EB6),
  'Background': const Color(0xFFEDEDED),
  'Background2': const Color(0xFFD9D9D9),
  'Srtoke': const Color(0xFFCCCCCC),
  'IconColor': const Color(0xFF646464),
  'DeleteColor': Colors.red,
  'EditColor': Colors.green,
  'CancelColor': Colors.blue,
  'SelectedCard': const Color(0xFFFFFFFF),
  'StatusNone': const Color(0xFF0CD026),
  'StatusNoneCard': const Color(0xFFCEE9CF),
  'StatusInprogress': const Color(0xFF41B60A),
  'StatusInprogressCard': const Color(0xFFEDEDED),
  'StatusVerify': const Color(0xFF510CD0),
  'StatusVerifyCard': const Color(0xFF510CD0),
  'StatusCompleted': const Color(0xFFD07B0C),
  'StatusCompletedCard': const Color(0xFFD07B0C),
  'StatusCalceled': const Color(0xFF7A7774),
  'StatusCalceledCard': const Color(0xFF7A7774),
};
